version: '3'

services:
  server:
    image: "pilshchikov/stress-report-front:latest"
    depends_on:
      - db
    ports:
      - "9999:9999"
    environment:
      - "DB_URL=db:5433"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
  frontend:
    image: "pilshchikov/stress-report-front:latest"
    depends_on:
      - server
    ports:
      - "80:80"
  db:
    image: "yugabytedb/yugabyte:latest"
    volumes:
      - "${DB_PATH}:/db_data"
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    command: "./bin/yugabyted start --base_dir=/db_data --daemon=false"
