version: '3'

services:
  server:
    image: "ghcr.io/pilshchikov/stress-report/server:latest"
    depends_on:
      - db
    ports:
      - "9999:9999"
    environment:
      - "DB_URL=db:5433"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
  frontend:
    image: "ghcr.io/pilshchikov/stress-report/frontend:latest"
    depends_on:
      - server
    ports:
      - "80:80"
  files:
    image: "ghcr.io/pilshchikov/stress-report/files:latest"
    depends_on:
      - db
    ports:
      - "9998:9998"
    environment:
      - "STORAGE_PATH=/files_dir"
      - "DB_USER=yugabyte"
      - "DB_PASSWORD=yugabyte"
      - "DB_NAME=postgres"
      - "DB_HOST=server"
      - "DB_PORT=5433"
    volumes:
      - "${FILES_DIR}:/files_dir"
  db:
    image: "yugabytedb/yugabyte:latest"
    volumes:
      - "${DB_PATH}:/db_data"
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    command: "./bin/yugabyted start --base_dir=/db_data --daemon=false"
