version: '3'

services:
  server:
    image: "ghcr.io/pilshchikov/stress-report/server:${SERVER_VERSION:-latest}"
    depends_on:
      - db
    ports:
      - "9999:9999"
    environment:
      - "DB_URL=db:5433"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "FILES_URL=files:9998"
      - "SETUP_FILE=/setup.sql"
    volumes:
      - "${SETUP_DB_FILE_PATH:-/tmp}:/setup.sql:ro"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 10m
  frontend:
    image: "ghcr.io/pilshchikov/stress-report/frontend:${FRONTEND_VERSION:-latest}"
    depends_on:
      - server
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 10m
  files:
    image: "ghcr.io/pilshchikov/stress-report/files:${FILES_VERISON:-latest}"
    depends_on:
      - db
    ports:
      - "9998:9998"
    environment:
      - "STORAGE_PATH=/files_dir"
      - "DB_USER=yugabyte"
      - "DB_PASSWORD=yugabyte"
      - "DB_NAME=postgres"
      - "DB_HOST=db"
      - "DB_PORT=5433"
    volumes:
      - "${FILES_DIR:-/tmp/files}:/files_dir"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 10m
  db:
    image: "yugabytedb/yugabyte:${YUGABYTE_VERSION:-latest}"
    volumes:
      - "${DB_PATH:-/tmp/db}:/db_data"
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    command: "./bin/yugabyted start --base_dir=/db_data --daemon=false"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 10m
