version: '3'

services:
  server:
    image: "server:latest"
    depends_on:
      - db
    build:
      dockerfile: backend/server/build/Dockerfile
      context: .
    ports:
      - "9999:9999"
    environment:
      - "DB_URL=db:5433"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
  frontend:
    image: "frontend:latest"
    depends_on:
      - server
    ports:
      - "80:80"
    build:
      dockerfile: frontend/build/Dockerfile
      context: .
  db:
    image: "yugabytedb/yugabyte:latest"
    volumes:
      - "/Users/spilshchikov/workplace/trash/yb/db:/db_data"
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    command: "./bin/yugabyted start --base_dir=/db_data --daemon=false"
