name: Build and push images

on:
  workflow_dispatch:
    inputs:
      frontend_version:
        description: Frontend image version
        default: ''
      server_version:
        description: Server image version
        default: ''

jobs:
  frontend:
    runs-on: ubuntu-latest
    if: github.event.inputs.frontend_version != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend/build/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/frontend:${{ github.event.inputs.frontend_version }}

  server:
    runs-on: ubuntu-latest
    if: github.event.inputs.server_version != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/server/build/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/server:${{ github.event.inputs.server_version }}
